const armorDash = {
  layouts: {
    lg: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 1,
        i: "30db4498aa",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 2,
        i: "11e55a5b31",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 3,
        i: "7cf8de0751",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 4,
        i: "6bc7d9f20e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 5,
        i: "a5fa0a71c9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 6,
        i: "7773078e96",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 7,
        i: "5a3e2264f4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 8,
        i: "0cf75b5f73",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 9,
        i: "00b25559a7",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 10,
        i: "124197690d",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 11,
        i: "b58b0693b1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 12,
        i: "d6c63b2ff0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 13,
        i: "a000f4e1ac",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 14,
        i: "28fedd94d3",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 15,
        i: "627ccd6fd0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 16,
        i: "5bbff8e2ef",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 17,
        i: "2eca0f72e6",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 18,
        i: "4323adf9eb",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 19,
        i: "a6cb02f465",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 20,
        i: "f0cfa26ffc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 21,
        i: "6300fa6de5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 22,
        i: "bd84ffa8bc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 23,
        i: "d318ae068c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 24,
        i: "6c90333920",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 25,
        i: "1a03850d22",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 26,
        i: "91cf71b2b8",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 27,
        i: "5b0afeaa2b",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 28,
        i: "bf2b846f4a",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 29,
        i: "70422ea4eb",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 30,
        i: "e3d33f8bda",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 31,
        i: "fb2206d4ba",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 32,
        i: "4b68c863e5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 33,
        i: "83b45f2787",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 34,
        i: "891f3572df",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 35,
        i: "f641549a20",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 36,
        i: "4671120ab7",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 37,
        i: "314aaa2522",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 38,
        i: "1e341ec4e3",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 39,
        i: "b6e3df97a2",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 40,
        i: "816a92edb3",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 41,
        i: "cbc444cd4e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 42,
        i: "c9156815f4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 43,
        i: "680d308e40",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 44,
        i: "f1017431c3",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 45,
        i: "d599a6fec2",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 46,
        i: "a35ddd9577",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 47,
        i: "0d00cb4bcd",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 48,
        i: "3f10f81f8e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 49,
        i: "cc6bc411a5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 50,
        i: "ac651ea5c1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 51,
        i: "6fd3418196",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 52,
        i: "e552f2ba40",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 53,
        i: "93c85bbd84",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 54,
        i: "a6f652c756",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 55,
        i: "3f84cb4035",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 56,
        i: "afea9c01ae",
        moved: false,
        static: false,
      },
    ],
    md: [],
    sm: [],
    xs: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 3,
        h: 2,
        x: 0,
        y: 3,
        i: "30db4498aa",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 5,
        y: 3,
        i: "11e55a5b31",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 3,
        i: "7cf8de0751",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 6,
        y: 3,
        i: "6bc7d9f20e",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 2,
        x: 0,
        y: 1,
        i: "a5fa0a71c9",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 1,
        x: 0,
        y: 6,
        i: "7773078e96",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 3,
        y: 6,
        i: "5a3e2264f4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 5,
        y: 6,
        i: "0cf75b5f73",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 6,
        i: "00b25559a7",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 3,
        y: 7,
        i: "124197690d",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 1,
        x: 0,
        y: 7,
        i: "b58b0693b1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 5,
        y: 7,
        i: "d6c63b2ff0",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 7,
        i: "a000f4e1ac",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 1,
        x: 0,
        y: 8,
        i: "28fedd94d3",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 3,
        y: 8,
        i: "627ccd6fd0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 5,
        y: 8,
        i: "5bbff8e2ef",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 8,
        i: "2eca0f72e6",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 9,
        i: "4323adf9eb",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 5,
        i: "a6cb02f465",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 1,
        x: 0,
        y: 10,
        i: "f0cfa26ffc",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 3,
        y: 10,
        i: "6300fa6de5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 5,
        y: 10,
        i: "bd84ffa8bc",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 10,
        i: "d318ae068c",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 1,
        x: 0,
        y: 11,
        i: "6c90333920",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 3,
        y: 11,
        i: "1a03850d22",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 5,
        y: 11,
        i: "91cf71b2b8",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 11,
        i: "5b0afeaa2b",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 1,
        x: 0,
        y: 12,
        i: "bf2b846f4a",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 3,
        y: 12,
        i: "70422ea4eb",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 12,
        i: "e3d33f8bda",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 5,
        y: 12,
        i: "fb2206d4ba",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 1,
        x: 0,
        y: 13,
        i: "4b68c863e5",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 3,
        y: 13,
        i: "83b45f2787",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 5,
        y: 13,
        i: "891f3572df",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 13,
        i: "f641549a20",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 1,
        x: 0,
        y: 14,
        i: "4671120ab7",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 3,
        y: 14,
        i: "314aaa2522",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 5,
        y: 14,
        i: "1e341ec4e3",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 14,
        i: "b6e3df97a2",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 15,
        i: "816a92edb3",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 1,
        x: 0,
        y: 16,
        i: "cbc444cd4e",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 3,
        y: 16,
        i: "c9156815f4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 5,
        y: 16,
        i: "680d308e40",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 16,
        i: "f1017431c3",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 1,
        x: 0,
        y: 17,
        i: "d599a6fec2",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 3,
        y: 17,
        i: "a35ddd9577",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 5,
        y: 17,
        i: "0d00cb4bcd",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 17,
        i: "3f10f81f8e",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 1,
        x: 0,
        y: 18,
        i: "cc6bc411a5",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 3,
        y: 18,
        i: "ac651ea5c1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 5,
        y: 18,
        i: "6fd3418196",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 18,
        i: "e552f2ba40",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 1,
        x: 0,
        y: 19,
        i: "93c85bbd84",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 3,
        y: 19,
        i: "a6f652c756",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 5,
        y: 19,
        i: "3f84cb4035",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 19,
        i: "afea9c01ae",
        moved: false,
        static: false,
      },
    ],
    xxs: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 3,
        i: "30db4498aa",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 3,
        i: "11e55a5b31",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 3,
        i: "7cf8de0751",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 3,
        i: "6bc7d9f20e",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 1,
        i: "a5fa0a71c9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 6,
        i: "7773078e96",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 6,
        i: "5a3e2264f4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 6,
        i: "0cf75b5f73",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 6,
        i: "00b25559a7",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 8,
        i: "124197690d",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 8,
        i: "b58b0693b1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 8,
        i: "d6c63b2ff0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 8,
        i: "a000f4e1ac",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 10,
        i: "28fedd94d3",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 10,
        i: "627ccd6fd0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 10,
        i: "5bbff8e2ef",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 10,
        i: "2eca0f72e6",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 12,
        i: "4323adf9eb",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 5,
        i: "a6cb02f465",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 13,
        i: "f0cfa26ffc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 13,
        i: "6300fa6de5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 13,
        i: "bd84ffa8bc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 13,
        i: "d318ae068c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 15,
        i: "6c90333920",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 15,
        i: "1a03850d22",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 15,
        i: "91cf71b2b8",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 15,
        i: "5b0afeaa2b",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 17,
        i: "bf2b846f4a",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 17,
        i: "70422ea4eb",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 17,
        i: "e3d33f8bda",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 17,
        i: "fb2206d4ba",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 19,
        i: "4b68c863e5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 19,
        i: "83b45f2787",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 19,
        i: "891f3572df",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 19,
        i: "f641549a20",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 21,
        i: "4671120ab7",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 21,
        i: "314aaa2522",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 21,
        i: "1e341ec4e3",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 21,
        i: "b6e3df97a2",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 23,
        i: "816a92edb3",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 24,
        i: "cbc444cd4e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 24,
        i: "c9156815f4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 24,
        i: "680d308e40",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 24,
        i: "f1017431c3",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 26,
        i: "d599a6fec2",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 26,
        i: "a35ddd9577",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 26,
        i: "0d00cb4bcd",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 26,
        i: "3f10f81f8e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 28,
        i: "cc6bc411a5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 28,
        i: "ac651ea5c1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 28,
        i: "6fd3418196",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 28,
        i: "e552f2ba40",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 30,
        i: "93c85bbd84",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 30,
        i: "a6f652c756",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 30,
        i: "3f84cb4035",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 30,
        i: "afea9c01ae",
        moved: false,
        static: false,
      },
    ],
  },
  widgets: [
    {
      id: "30db4498aa",
      content: "## **<u>Type</u>**",
    },
    {
      id: "11e55a5b31",
      content: "## **🪙**",
    },
    {
      id: "7cf8de0751",
      content: "## **<u>AC</u>**",
    },
    {
      id: "6bc7d9f20e",
      content: "## 🏋️/ 🥷",
    },
    {
      id: "a5fa0a71c9",
      content: "## 🛡️ Armor 🛡️",
    },
    {
      id: "7773078e96",
      content: "Padded",
    },
    {
      id: "5a3e2264f4",
      content: "11+Dex",
    },
    {
      id: "0cf75b5f73",
      content: "5gp",
    },
    {
      id: "00b25559a7",
      content: "Na / Dis",
    },
    {
      id: "124197690d",
      content: "11+Dex",
    },
    {
      id: "b58b0693b1",
      content: "Leather",
    },
    {
      id: "d6c63b2ff0",
      content: "10gp",
    },
    {
      id: "a000f4e1ac",
      content: "Na / Na",
    },
    {
      id: "28fedd94d3",
      content: "Studded Leather",
    },
    {
      id: "627ccd6fd0",
      content: "11+Dex",
    },
    {
      id: "5bbff8e2ef",
      content: "45gp",
    },
    {
      id: "2eca0f72e6",
      content: "Na / Na",
    },
    {
      id: "4323adf9eb",
      content: "*🛡️ MEDIUM 🛡️*",
    },
    {
      id: "a6cb02f465",
      content: "*🛡️ LIGHT 🛡️*",
    },
    {
      id: "f0cfa26ffc",
      content: "Hide",
    },
    {
      id: "6300fa6de5",
      content: "12+Dex(Max2)",
    },
    {
      id: "bd84ffa8bc",
      content: "10gp",
    },
    {
      id: "d318ae068c",
      content: "Na / Na",
    },
    {
      id: "6c90333920",
      content: "Chain Shirt",
    },
    {
      id: "1a03850d22",
      content: "13+Dex(Max2)",
    },
    {
      id: "91cf71b2b8",
      content: "50gp",
    },
    {
      id: "5b0afeaa2b",
      content: "Na / Na",
    },
    {
      id: "bf2b846f4a",
      content: "Scale Mail",
    },
    {
      id: "70422ea4eb",
      content: "14+Dex(Max2)",
    },
    {
      id: "e3d33f8bda",
      content: "Na / Dis",
    },
    {
      id: "fb2206d4ba",
      content: "50gp",
    },
    {
      id: "4b68c863e5",
      content: "Breastplate",
    },
    {
      id: "83b45f2787",
      content: "14+Dex(Max2)",
    },
    {
      id: "891f3572df",
      content: "400gp",
    },
    {
      id: "f641549a20",
      content: "Na / Na",
    },
    {
      id: "4671120ab7",
      content: "Half Plate",
    },
    {
      id: "314aaa2522",
      content: "15+Dex(Max2)",
    },
    {
      id: "1e341ec4e3",
      content: "750gp",
    },
    {
      id: "b6e3df97a2",
      content: "Na / Dis",
    },
    {
      id: "816a92edb3",
      content: "*🛡️ HEAVY 🛡️*",
    },
    {
      id: "cbc444cd4e",
      content: "Ring Mail",
    },
    {
      id: "c9156815f4",
      content: "14",
    },
    {
      id: "680d308e40",
      content: "30gp",
    },
    {
      id: "f1017431c3",
      content: "Na / Dis",
    },
    {
      id: "d599a6fec2",
      content: "Chain Mail",
    },
    {
      id: "a35ddd9577",
      content: "16",
    },
    {
      id: "0d00cb4bcd",
      content: "75gp",
    },
    {
      id: "3f10f81f8e",
      content: "13 / Dis",
    },
    {
      id: "cc6bc411a5",
      content: "Splint",
    },
    {
      id: "ac651ea5c1",
      content: "17",
    },
    {
      id: "6fd3418196",
      content: "200gp",
    },
    {
      id: "e552f2ba40",
      content: "15 / Dis",
    },
    {
      id: "93c85bbd84",
      content: "Plate",
    },
    {
      id: "a6f652c756",
      content: "18",
    },
    {
      id: "3f84cb4035",
      content: "1.5k",
    },
    {
      id: "afea9c01ae",
      content: "15 / Dis",
    },
  ],
  isLocked: true,
};

export default armorDash;
