const fifthEditionCharTemplate = {
  layouts: {
    lg: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 1,
        i: "2EB3jHESK0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 2,
        i: "6HJpLNCrAc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 3,
        i: "CwvVBR9eut",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 4,
        i: "4umfSLzahR",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 5,
        i: "1UQhC7sESM",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 6,
        i: "5Tz8YPDhc7",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 7,
        i: "xEd6NQvMrA",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 8,
        i: "5aP4Zagy8Y",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 9,
        i: "Tpk8gMv6tK",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 10,
        i: "2af9YxweIT",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 11,
        i: "gNrWHFFV48",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 12,
        i: "BUzi71KcGJ",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 13,
        i: "fbyLNhDZQ4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 14,
        i: "E8vt1oXcR6",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 15,
        i: "pbTjzir3LZ",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 16,
        i: "QUReQLTskE",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 17,
        i: "4fp71wl4DT",
        moved: false,
        static: false,
      },
    ],
    md: [],
    sm: [],
    xs: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 7,
        h: 1,
        x: 1,
        y: 0,
        i: "2EB3jHESK0",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 7,
        x: 0,
        y: 1,
        i: "6HJpLNCrAc",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 7,
        x: 3,
        y: 1,
        i: "CwvVBR9eut",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 8,
        i: "4umfSLzahR",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 9,
        i: "1UQhC7sESM",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 4,
        y: 9,
        i: "5Tz8YPDhc7",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 9,
        i: "xEd6NQvMrA",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 4,
        x: 0,
        y: 10,
        i: "5aP4Zagy8Y",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 4,
        x: 2,
        y: 10,
        i: "Tpk8gMv6tK",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 4,
        x: 4,
        y: 10,
        i: "2af9YxweIT",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 4,
        x: 6,
        y: 10,
        i: "gNrWHFFV48",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 8,
        x: 0,
        y: 14,
        i: "BUzi71KcGJ",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 8,
        x: 2,
        y: 14,
        i: "fbyLNhDZQ4",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 8,
        x: 4,
        y: 14,
        i: "E8vt1oXcR6",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 16,
        x: 0,
        y: 22,
        i: "pbTjzir3LZ",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 16,
        x: 3,
        y: 22,
        i: "QUReQLTskE",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 11,
        x: 0,
        y: 38,
        i: "4fp71wl4DT",
        moved: false,
        static: false,
      },
    ],
    xxs: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 1,
        i: "2EB3jHESK0",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 9,
        x: 0,
        y: 2,
        i: "6HJpLNCrAc",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 9,
        x: 2,
        y: 2,
        i: "CwvVBR9eut",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 11,
        i: "4umfSLzahR",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 16,
        i: "1UQhC7sESM",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 0,
        y: 12,
        i: "5Tz8YPDhc7",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 12,
        i: "xEd6NQvMrA",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 3,
        x: 0,
        y: 17,
        i: "5aP4Zagy8Y",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 3,
        x: 2,
        y: 17,
        i: "Tpk8gMv6tK",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 3,
        x: 0,
        y: 13,
        i: "2af9YxweIT",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 3,
        x: 2,
        y: 13,
        i: "gNrWHFFV48",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 9,
        x: 0,
        y: 20,
        i: "BUzi71KcGJ",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 9,
        x: 2,
        y: 20,
        i: "fbyLNhDZQ4",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 6,
        x: 0,
        y: 29,
        i: "E8vt1oXcR6",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 17,
        x: 0,
        y: 35,
        i: "pbTjzir3LZ",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 17,
        x: 2,
        y: 35,
        i: "QUReQLTskE",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 11,
        x: 0,
        y: 52,
        i: "4fp71wl4DT",
        moved: false,
        static: false,
      },
    ],
  },
  widgets: [
    {
      id: "2EB3jHESK0",
      content: "## Character Name",
    },
    {
      id: "6HJpLNCrAc",
      content:
        "![File\\:Profile avatar placeholder large.png](https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png?20150327203541)",
    },
    {
      id: "CwvVBR9eut",
      content:
        '*"A Character Quote"*\n\n***\n\n**<u>Level</u>**: *1* **<u>Class</u>**: *Fighter* **<u>Background</u>**: *Gladiator* **<u>Race</u>**: *Hobgoblin* **<u>Alignment</u>**: *Chaotic Good*&#x20;\n\n**<u>Armor</u>**: *Light Armor*\n\n**<u>Weapons</u>**: *Simple Weapons*\n\n**<u>Tools</u>**: *Calligrapher\'s Supplies*\n\n**<u>Languages</u>**: *Common, Goblin*',
    },
    {
      id: "4umfSLzahR",
      content: "* [x] Inspiration",
    },
    {
      id: "1UQhC7sESM",
      content: "## Death 💀 Saves",
    },
    {
      id: "5Tz8YPDhc7",
      content: "## **AC 🛡️**",
    },
    {
      id: "xEd6NQvMrA",
      content: "## HP ❤️",
    },
    {
      id: "5aP4Zagy8Y",
      content: "* [ ] Fail 1\n* [ ] Fail 2\n* [ ] Fail 3",
    },
    {
      id: "Tpk8gMv6tK",
      content: "* [ ] Save 1\n* [ ] Save 2\n* [ ] Save 3",
    },
    {
      id: "2af9YxweIT",
      content: "# 10",
    },
    {
      id: "gNrWHFFV48",
      content: "`100` Max\n\n`100` Current\n\n`100` Temp",
    },
    {
      id: "BUzi71KcGJ",
      content:
        '### Ability Scores\n\n## `10` STR:dice[+1]{isModNotation="true"}&#x20;\n\n## `10` DEX:dice[+1]{isModNotation="true"}&#x20;\n\n## `10` CON:dice[+1]{isModNotation="true"}&#x20;\n\n## `10` INT:dice[+1]{isModNotation="true"}&#x20;\n\n## `10` WIS:dice[+1]{isModNotation="true"}&#x20;\n\n## `10` CHA:dice[+1]{isModNotation="true"}&#x20;',
    },
    {
      id: "fbyLNhDZQ4",
      content:
        '### Saving Throws\n\n* [ ] **STR** :dice[+1]{isModNotation="true"} &#x20;\n* [ ] **DEX** :dice[+1]{isModNotation="true"}&#x20;\n* [ ] **CON** :dice[+1]{isModNotation="true"}&#x20;\n* [ ] **INT** :dice[+1]{isModNotation="true"}&#x20;\n* [ ] **WIS** :dice[+1]{isModNotation="true"}&#x20;\n* [ ] **CHA** :dice[+1]{isModNotation="true"}&#x20;',
    },
    {
      id: "E8vt1oXcR6",
      content:
        '**Initiative**: :dice[+1]{isModNotation="true"}\n\n**Proficiency**: :dice[+1]{isModNotation="true"}\n\n**Speed**: `30ft Walk`\n\n**XP**: `(milestone)`\n\n**Passive Perception**: `10`\n\n**Passive Insight**: `10`&#x20;\n\n**Passive Investigation**: `10`',
    },
    {
      id: "pbTjzir3LZ",
      content:
        '## Skills\n\n* [ ] Acrobatics :dice[+0]{isModNotation="true"}&#x20;\n* [ ] Animal Handle :dice[+0]{isModNotation="true"}\n* [ ] Arcana :dice[+0]{isModNotation="true"}\n* [ ] Athletics :dice[+0]{isModNotation="true"}\n* [ ] Deception :dice[+0]{isModNotation="true"}\n* [ ] History :dice[+0]{isModNotation="true"}\n* [ ] Insight :dice[+0]{isModNotation="true"}\n* [ ] Intimidation :dice[+0]{isModNotation="true"}\n* [ ] Investigation :dice[+0]{isModNotation="true"}\n* [ ] Medicine :dice[+0]{isModNotation="true"}\n* [ ] Nature :dice[+0]{isModNotation="true"}\n* [ ] Perception :dice[+0]{isModNotation="true"}\n* [ ] Performance :dice[+0]{isModNotation="true"}\n* [ ] Persuasion :dice[+0]{isModNotation="true"}\n* [ ] Religion :dice[+0]{isModNotation="true"}\n* [ ] Sleight of Hand :dice[+0]{isModNotation="true"}\n* [ ] Stealth :dice[+0]{isModNotation="true"}\n* [ ] Survival :dice[+0]{isModNotation="true"}',
    },
    {
      id: "QUReQLTskE",
      content:
        "## Actions\n\n\n\n**<u>Chill Touch</u>**, 120ft Range, +10 to hit, 3d8 Necrotic\n\n**<u>Shocking Grasp</u>**, Range of Touch, +10 to hit, 3d8 Lightning&#x20;\n\n**<u>Unarmed Strike</u>**, 5ft Reach, +4 to hit, 1 point bludgeoning\n\n***(Enter your actions in this space however you'd like. This is just one potential way to list them out.)***",
    },
    {
      id: "4fp71wl4DT",
      content:
        '## Spells\n\nSpell Saves: :dice[DC14]{isDCNotation="true"}&#x20;\n\nSpell Attack: :dice[+3]{isModNotation="true"}&#x20;\n\n### <u>Cantrips</u>\n\n*Chill Touch, Fire Bolt, Guidance, Mind Sliver, Shocking Grasp, Shocking Grasp, Spare the Dying, Thaumaturgy*\n\n### <u>1st Level</u>\n\n`0` **/** `4` **Slots Used**\n\n*Alarm, Bless, Comprehend Languages, Cure Wounds, Detect Magic, Disguise Self, Find Familiar, Fog Cloud*\n\n***(Enter your spells in this space however you\'d like. This is just one potential way to list them out.)***',
    },
  ],
  isLocked: true,
};

export default fifthEditionCharTemplate;
