const fifthEditionCharTemplate = {
  layouts: {
    lg: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 1,
        i: "4b619e3b2c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 2,
        i: "6c9dd4ae6e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 3,
        i: "751982e623",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 4,
        i: "6fa5f27116",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 5,
        i: "2414176383",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 6,
        i: "5bc345bbaa",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 7,
        i: "3dcdb01187",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 8,
        i: "cd7d219da9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 9,
        i: "2d984fc280",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 10,
        i: "dd62953d58",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 11,
        i: "9535451cb6",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 12,
        i: "a95c2c45c6",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 13,
        i: "c8beae633b",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 14,
        i: "052ae296ed",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 15,
        i: "30782f6c94",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 16,
        i: "35a47f955f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 17,
        i: "87efcbb28d",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 18,
        i: "f0782456c9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 19,
        i: "baf37639be",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 20,
        i: "e8f031def5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 21,
        i: "a32dc3607c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 22,
        i: "f0d19d3e17",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 23,
        i: "95265fa8fd",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 24,
        i: "972fb93e57",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 25,
        i: "8ca6960ea0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 26,
        i: "6f07641441",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 27,
        i: "e1d35dd172",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 28,
        i: "dcf197fbf2",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 29,
        i: "788b76f662",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 30,
        i: "5dea12f5d7",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 31,
        i: "adc1acd5a0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 32,
        i: "35c6ea544f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 33,
        i: "9b768c4503",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 34,
        i: "f3526eb57f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 35,
        i: "10d77a6b66",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 36,
        i: "0f1a9020e3",
        moved: false,
        static: false,
      },
    ],
    md: [],
    sm: [],
    xs: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 8,
        h: 2,
        x: 0,
        y: 1,
        i: "4b619e3b2c",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 4,
        y: 3,
        i: "6c9dd4ae6e",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 0,
        y: 3,
        i: "751982e623",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 12,
        i: "6fa5f27116",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 22,
        i: "2414176383",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 14,
        i: "5bc345bbaa",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 20,
        i: "3dcdb01187",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 16,
        i: "cd7d219da9",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 18,
        i: "2d984fc280",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 4,
        y: 4,
        i: "dd62953d58",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 4,
        y: 14,
        i: "9535451cb6",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 4,
        x: 4,
        y: 7,
        i: "a95c2c45c6",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 8,
        x: 4,
        y: 16,
        i: "c8beae633b",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 4,
        y: 15,
        i: "052ae296ed",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 6,
        i: "30782f6c94",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 4,
        y: 6,
        i: "35a47f955f",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 4,
        y: 12,
        i: "87efcbb28d",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 11,
        i: "f0782456c9",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 4,
        y: 11,
        i: "baf37639be",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 5,
        i: "e8f031def5",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 4,
        x: 6,
        y: 7,
        i: "a32dc3607c",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 3,
        i: "f0d19d3e17",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 4,
        i: "95265fa8fd",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 3,
        i: "972fb93e57",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 11,
        i: "8ca6960ea0",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 4,
        i: "6f07641441",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 0,
        y: 4,
        i: "e1d35dd172",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 14,
        i: "dcf197fbf2",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 12,
        i: "788b76f662",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 4,
        x: 0,
        y: 7,
        i: "5dea12f5d7",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 4,
        x: 2,
        y: 7,
        i: "adc1acd5a0",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 6,
        i: "35c6ea544f",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 4,
        y: 13,
        i: "9b768c4503",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 6,
        y: 13,
        i: "f3526eb57f",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 24,
        i: "10d77a6b66",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 16,
        x: 0,
        y: 25,
        i: "0f1a9020e3",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 4,
        y: 24,
        i: "3504388fb2",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 4,
        y: 25,
        i: "e24a632578",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 4,
        y: 26,
        i: "3a4ef70588",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 4,
        y: 27,
        i: "5c69af9e11",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 4,
        y: 29,
        i: "cfe44edcfd",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 4,
        y: 28,
        i: "ae4e0813f1",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 4,
        y: 30,
        i: "f992107b09",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 10,
        x: 4,
        y: 31,
        i: "41894021fe",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 50,
        i: "5de2862893",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 9,
        x: 0,
        y: 51,
        i: "5fffed03d5",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 41,
        i: "dc46a3f65b",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 8,
        x: 0,
        y: 42,
        i: "4239290677",
        moved: false,
        static: false,
      },
    ],
    xxs: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 1,
        i: "4b619e3b2c",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 0,
        y: 3,
        i: "6c9dd4ae6e",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 0,
        y: 2,
        i: "751982e623",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 23,
        i: "6fa5f27116",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 33,
        i: "2414176383",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 25,
        i: "5bc345bbaa",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 31,
        i: "3dcdb01187",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 27,
        i: "cd7d219da9",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 29,
        i: "2d984fc280",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 0,
        y: 5,
        i: "dd62953d58",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 0,
        y: 20,
        i: "9535451cb6",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 3,
        x: 0,
        y: 13,
        i: "a95c2c45c6",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 6,
        x: 0,
        y: 36,
        i: "c8beae633b",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 35,
        i: "052ae296ed",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 12,
        i: "30782f6c94",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 0,
        y: 12,
        i: "35a47f955f",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 18,
        i: "87efcbb28d",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 22,
        i: "f0782456c9",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 16,
        i: "baf37639be",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 4,
        x: 0,
        y: 16,
        i: "e8f031def5",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 3,
        x: 2,
        y: 13,
        i: "a32dc3607c",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 2,
        i: "f0d19d3e17",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 4,
        i: "95265fa8fd",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 3,
        i: "972fb93e57",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 17,
        i: "8ca6960ea0",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 5,
        i: "6f07641441",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 0,
        y: 4,
        i: "e1d35dd172",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 0,
        y: 21,
        i: "dcf197fbf2",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 19,
        i: "788b76f662",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 4,
        x: 0,
        y: 8,
        i: "5dea12f5d7",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 4,
        x: 2,
        y: 8,
        i: "adc1acd5a0",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 6,
        i: "35c6ea544f",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 20,
        i: "9b768c4503",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 1,
        x: 2,
        y: 21,
        i: "f3526eb57f",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 42,
        i: "10d77a6b66",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 18,
        x: 0,
        y: 43,
        i: "0f1a9020e3",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 61,
        i: "3504388fb2",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 62,
        i: "e24a632578",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 63,
        i: "3a4ef70588",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 64,
        i: "5c69af9e11",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 66,
        i: "cfe44edcfd",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 65,
        i: "ae4e0813f1",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 67,
        i: "f992107b09",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 11,
        x: 0,
        y: 69,
        i: "41894021fe",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 90,
        i: "5de2862893",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 16,
        x: 0,
        y: 91,
        i: "5fffed03d5",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 80,
        i: "dc46a3f65b",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 9,
        x: 0,
        y: 81,
        i: "4239290677",
        moved: false,
        static: false,
      },
    ],
  },
  widgets: [
    {
      id: "4b619e3b2c",
      content: "## Name",
    },
    {
      id: "6c9dd4ae6e",
      content: "**Race**",
    },
    {
      id: "751982e623",
      content: "**Class**",
    },
    {
      id: "6fa5f27116",
      content: "## `+1` STR `10`",
    },
    {
      id: "2414176383",
      content: "## `+1` CHA `10`",
    },
    {
      id: "5bc345bbaa",
      content: "## `+1` DEX `10`",
    },
    {
      id: "3dcdb01187",
      content: "## `+1` WIS `10`",
    },
    {
      id: "cd7d219da9",
      content: "## `+1` CON `10`",
    },
    {
      id: "2d984fc280",
      content: "## `+1` INT `10`",
    },
    {
      id: "dd62953d58",
      content: "**Background**",
    },
    {
      id: "9535451cb6",
      content: "**XP**",
    },
    {
      id: "a95c2c45c6",
      content: "# 10",
    },
    {
      id: "c8beae633b",
      content:
        "* [ ] `+0` Strength\n* [ ] `+0` Dexterity\n* [ ] `+0` Constitution\n* [ ] `+0` Intelligence\n* [ ] `+0` Wisdom\n* [ ] `+0` Charisma",
    },
    {
      id: "052ae296ed",
      content: "## Saving Throws",
    },
    {
      id: "30782f6c94",
      content: "## HP ❤️",
    },
    {
      id: "35a47f955f",
      content: "## **AC 🛡️**",
    },
    {
      id: "87efcbb28d",
      content: "**Initiative**",
    },
    {
      id: "f0782456c9",
      content: "## Ability Scores",
    },
    {
      id: "baf37639be",
      content: "**Proficiency**&#x20;",
    },
    {
      id: "e8f031def5",
      content: "* [ ] Inspiration",
    },
    {
      id: "a32dc3607c",
      content: "`100` Max\n\n`100` Current\n\n`100` Temp",
    },
    {
      id: "f0d19d3e17",
      content: "",
    },
    {
      id: "95265fa8fd",
      content: "",
    },
    {
      id: "972fb93e57",
      content: "",
    },
    {
      id: "8ca6960ea0",
      content: "`+4`",
    },
    {
      id: "6f07641441",
      content: "",
    },
    {
      id: "e1d35dd172",
      content: "**Level**",
    },
    {
      id: "dcf197fbf2",
      content: "`(milestone)`",
    },
    {
      id: "788b76f662",
      content: "`+8`",
    },
    {
      id: "5dea12f5d7",
      content: "* [ ] Fail 1\n* [ ] Fail 2\n* [ ] Fail 3",
    },
    {
      id: "adc1acd5a0",
      content: "* [ ] Save 1\n* [ ] Save 2\n* [ ] Save 3",
    },
    {
      id: "35c6ea544f",
      content: "## Death 💀 Saves",
    },
    {
      id: "9b768c4503",
      content: "**Speed**",
    },
    {
      id: "f3526eb57f",
      content: "`30ft Walk`",
    },
    {
      id: "10d77a6b66",
      content: "## Skills",
    },
    {
      id: "0f1a9020e3",
      content:
        "* [ ] `+0` Acrobatics\n* [ ] `+0` Animal Handling\n* [ ] `+0` Arcana\n* [ ] `+0` Athletics\n* [ ] `+0` Deception\n* [ ] `+0` History\n* [ ] `+0` Insight\n* [ ] `+0` Intimidation\n* [ ] `+0` Investigation\n* [ ] `+0` Medicine\n* [ ] `+0` Nature\n* [ ] `+0` Perception\n* [ ] `+0` Performance\n* [ ] `+0` Persuasion\n* [ ] `+0` Religion\n* [ ] `+0` Sleight of Hand\n* [ ] `+0` Stealth\n* [ ] `+0` Survival",
    },
    {
      id: "3504388fb2",
      content: "**Passive Perception**",
    },
    {
      id: "e24a632578",
      content: "`10`",
    },
    {
      id: "3a4ef70588",
      content: "**Passive Insight**",
    },
    {
      id: "5c69af9e11",
      content: "`10`",
    },
    {
      id: "cfe44edcfd",
      content: "`10`",
    },
    {
      id: "ae4e0813f1",
      content: "**Passive Investigation**",
    },
    {
      id: "f992107b09",
      content: "**Proficiencies & Languages**",
    },
    {
      id: "41894021fe",
      content:
        "**<u>Armor</u>**\n\n*None*\n\n**<u>Weapons</u>**\n\n*None*\n\n**<u>Tools</u>**\n\n*None*\n\n**<u>Languages</u>**\n\n*Common*",
    },
    {
      id: "5de2862893",
      content: "## Spells",
    },
    {
      id: "5fffed03d5",
      content:
        "### <u>Cantrips</u>\n\n*Chill Touch, Fire Bolt, Guidance, Mind Sliver, Shocking Grasp, Shocking Grasp, Spare the Dying, Thaumaturgy*\n\n### <u>1st Level</u>\n\n`0` **/** `4` **Slots Used**\n\n*Alarm, Bless, Comprehend Languages, Cure Wounds, Detect Magic, Disguise Self, Find Familiar, Fog Cloud*\n\n*(Enter your spells in this space however you'd like. This is just one potential way to list them out.)*",
    },
    {
      id: "dc46a3f65b",
      content: "## Actions",
    },
    {
      id: "4239290677",
      content:
        "**<u>Chill Touch</u>**, 120ft Range, +10 to hit, 3d8 Necrotic\n\n**<u>Shocking Grasp</u>**, Range of Touch, +10 to hit, 3d8 Lightning&#x20;\n\n**<u>Unarmed Strike</u>**, 5ft Reach, +4 to hit, 1 point bludgeoning\n\n*(Enter your actions in this space however you'd like. This is just one potential way to list them out.)*",
    },
  ],
  isLocked: true,
};

export default fifthEditionCharTemplate;
