const martialWeaponsDashPremade = {
  layouts: {
    lg: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 1,
        i: "d5ce6b5379",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 2,
        i: "0e3cf44a7f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 3,
        i: "18f3580c70",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 4,
        i: "76c1b00605",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 5,
        i: "b4d859a59c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 6,
        i: "bf018c61bd",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 7,
        i: "7103c78fba",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 8,
        i: "f7147315fc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 9,
        i: "f30c37510c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 10,
        i: "4a71d65708",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 11,
        i: "78926fb23f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 12,
        i: "93523da019",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 13,
        i: "21ca77f398",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 14,
        i: "1ce4feba35",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 15,
        i: "4fcc0269d1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 16,
        i: "bb1a28c7e9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 17,
        i: "e1a31dab10",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 18,
        i: "5817103e3f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 19,
        i: "8c1b21c63e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 20,
        i: "5c69376534",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 21,
        i: "91c319b58f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 22,
        i: "b5332f99e0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 23,
        i: "d34083fadd",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 24,
        i: "aba7240085",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 25,
        i: "47344bb0ee",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 26,
        i: "b4e234f3c8",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 27,
        i: "83fdd103b9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 28,
        i: "2c70a86fcc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 29,
        i: "3a7bec4596",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 30,
        i: "4988fe75c6",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 31,
        i: "6c8a727f66",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 32,
        i: "cb4dcf6889",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 33,
        i: "026c9b7fb9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 34,
        i: "e879ba1772",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 35,
        i: "dd0637baff",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 36,
        i: "7d92fed9ca",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 37,
        i: "af3ae00f32",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 38,
        i: "f83adfa0a4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 39,
        i: "7095234177",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 40,
        i: "e53eb4dc8d",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 41,
        i: "5266c25067",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 42,
        i: "3a09c6b35f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 43,
        i: "6f01bf04ae",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 44,
        i: "40880d2424",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 45,
        i: "1451e7e6f4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 46,
        i: "5a90e2d138",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 47,
        i: "c09b8d6017",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 48,
        i: "0992628893",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 49,
        i: "d37f74a7a8",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 50,
        i: "930e9f345b",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 51,
        i: "c82867b745",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 52,
        i: "c8e550da12",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 53,
        i: "5dbba0fe80",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 54,
        i: "9186471baf",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 55,
        i: "f5bd10ee42",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 56,
        i: "19b3593ed5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 57,
        i: "dde0e8be14",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 58,
        i: "0269c95f63",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 59,
        i: "9cb15f60ba",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 60,
        i: "f69729e7b5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 61,
        i: "e627c1c5f0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 62,
        i: "d15926c8cb",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 63,
        i: "5f6ef96fc6",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 64,
        i: "fb5a6f0897",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 65,
        i: "d0e7c007f5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 66,
        i: "8d965cdf52",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 67,
        i: "7fb52e9770",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 68,
        i: "90a35fa878",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 69,
        i: "155ff2d875",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 70,
        i: "30cf12a087",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 71,
        i: "78cf00e1f9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 72,
        i: "6cf314bd85",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 73,
        i: "52a2bf75e7",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 74,
        i: "8ab672283a",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 75,
        i: "48fdd96cbc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 76,
        i: "388abfc1f8",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 77,
        i: "618e78a7b1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 78,
        i: "e65b21c429",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 79,
        i: "bbaa6ce2af",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 80,
        i: "10332c9560",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 81,
        i: "f20c00f856",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 82,
        i: "cf024244d9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 83,
        i: "ccdd313fec",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 84,
        i: "b73f5aa23c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 85,
        i: "5f9ce675c7",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 86,
        i: "86c8343c25",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 87,
        i: "6b0676bddf",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 88,
        i: "58b6908f5f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 89,
        i: "09f620d63f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 90,
        i: "5225b618ab",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 91,
        i: "126f717291",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 92,
        i: "5e4170fd3c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 93,
        i: "a757a9025f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 94,
        i: "eee0ca9574",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 95,
        i: "5d36ee57df",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 96,
        i: "4051731221",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 97,
        i: "807285da36",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 98,
        i: "159b206a7e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 99,
        i: "6fdd5f43c7",
        moved: false,
        static: false,
      },
    ],
    md: [],
    sm: [],
    xs: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 8,
        h: 2,
        x: 0,
        y: 1,
        i: "d5ce6b5379",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 3,
        i: "0e3cf44a7f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 3,
        i: "18f3580c70",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 3,
        i: "76c1b00605",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 3,
        i: "b4d859a59c",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 5,
        i: "bf018c61bd",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 6,
        i: "7103c78fba",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 6,
        i: "f7147315fc",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 6,
        i: "f30c37510c",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 6,
        i: "4a71d65708",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 8,
        i: "78926fb23f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 8,
        i: "93523da019",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 8,
        i: "21ca77f398",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 8,
        i: "1ce4feba35",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 10,
        i: "4fcc0269d1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 10,
        i: "bb1a28c7e9",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 10,
        i: "e1a31dab10",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 10,
        i: "5817103e3f",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 12,
        i: "8c1b21c63e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 12,
        i: "5c69376534",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 12,
        i: "91c319b58f",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 12,
        i: "b5332f99e0",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 14,
        i: "d34083fadd",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 14,
        i: "aba7240085",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 14,
        i: "47344bb0ee",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 14,
        i: "b4e234f3c8",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 16,
        i: "83fdd103b9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 16,
        i: "2c70a86fcc",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 16,
        i: "3a7bec4596",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 16,
        i: "4988fe75c6",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 18,
        i: "6c8a727f66",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 18,
        i: "cb4dcf6889",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 18,
        i: "026c9b7fb9",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 18,
        i: "e879ba1772",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 20,
        i: "dd0637baff",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 20,
        i: "7d92fed9ca",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 20,
        i: "af3ae00f32",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 20,
        i: "f83adfa0a4",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 22,
        i: "7095234177",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 22,
        i: "e53eb4dc8d",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 22,
        i: "5266c25067",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 22,
        i: "3a09c6b35f",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 24,
        i: "6f01bf04ae",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 24,
        i: "40880d2424",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 24,
        i: "1451e7e6f4",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 24,
        i: "5a90e2d138",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 42,
        i: "c09b8d6017",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 43,
        i: "0992628893",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 43,
        i: "d37f74a7a8",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 43,
        i: "930e9f345b",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 38,
        i: "c82867b745",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 45,
        i: "c8e550da12",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 45,
        i: "5dbba0fe80",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 45,
        i: "9186471baf",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 45,
        i: "f5bd10ee42",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 47,
        i: "19b3593ed5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 47,
        i: "dde0e8be14",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 47,
        i: "0269c95f63",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 47,
        i: "9cb15f60ba",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 49,
        i: "f69729e7b5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 49,
        i: "e627c1c5f0",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 49,
        i: "d15926c8cb",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 49,
        i: "5f6ef96fc6",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 26,
        i: "fb5a6f0897",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 26,
        i: "d0e7c007f5",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 26,
        i: "8d965cdf52",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 26,
        i: "7fb52e9770",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 28,
        i: "90a35fa878",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 28,
        i: "155ff2d875",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 28,
        i: "30cf12a087",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 28,
        i: "78cf00e1f9",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 30,
        i: "6cf314bd85",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 30,
        i: "52a2bf75e7",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 30,
        i: "8ab672283a",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 40,
        i: "48fdd96cbc",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 32,
        i: "388abfc1f8",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 32,
        i: "618e78a7b1",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 32,
        i: "e65b21c429",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 30,
        i: "bbaa6ce2af",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 34,
        i: "10332c9560",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 34,
        i: "f20c00f856",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 34,
        i: "cf024244d9",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 32,
        i: "ccdd313fec",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 36,
        i: "b73f5aa23c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 36,
        i: "5f9ce675c7",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 36,
        i: "86c8343c25",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 34,
        i: "6b0676bddf",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 38,
        i: "58b6908f5f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 38,
        i: "09f620d63f",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 38,
        i: "5225b618ab",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 36,
        i: "126f717291",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 40,
        i: "5e4170fd3c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 40,
        i: "a757a9025f",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 40,
        i: "eee0ca9574",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 43,
        i: "5d36ee57df",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 51,
        i: "4051731221",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 51,
        i: "807285da36",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 51,
        i: "159b206a7e",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 51,
        i: "6fdd5f43c7",
        moved: false,
        static: false,
      },
    ],
    xxs: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 1,
        i: "d5ce6b5379",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 3,
        i: "0e3cf44a7f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 3,
        i: "18f3580c70",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 3,
        i: "76c1b00605",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 3,
        i: "b4d859a59c",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 5,
        i: "bf018c61bd",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 6,
        i: "7103c78fba",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 6,
        i: "f7147315fc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 6,
        i: "f30c37510c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 6,
        i: "4a71d65708",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 9,
        i: "78926fb23f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 9,
        i: "93523da019",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 9,
        i: "21ca77f398",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 9,
        i: "1ce4feba35",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 12,
        i: "4fcc0269d1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 12,
        i: "bb1a28c7e9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 12,
        i: "e1a31dab10",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 12,
        i: "5817103e3f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 15,
        i: "8c1b21c63e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 15,
        i: "5c69376534",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 15,
        i: "91c319b58f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 15,
        i: "b5332f99e0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 18,
        i: "d34083fadd",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 18,
        i: "aba7240085",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 18,
        i: "47344bb0ee",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 18,
        i: "b4e234f3c8",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 21,
        i: "83fdd103b9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 21,
        i: "2c70a86fcc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 21,
        i: "3a7bec4596",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 21,
        i: "4988fe75c6",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 24,
        i: "6c8a727f66",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 24,
        i: "cb4dcf6889",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 24,
        i: "026c9b7fb9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 24,
        i: "e879ba1772",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 27,
        i: "dd0637baff",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 27,
        i: "7d92fed9ca",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 27,
        i: "af3ae00f32",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 27,
        i: "f83adfa0a4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 30,
        i: "7095234177",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 30,
        i: "e53eb4dc8d",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 30,
        i: "5266c25067",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 30,
        i: "3a09c6b35f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 33,
        i: "6f01bf04ae",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 33,
        i: "40880d2424",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 33,
        i: "1451e7e6f4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 33,
        i: "5a90e2d138",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 60,
        i: "c09b8d6017",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 61,
        i: "0992628893",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 45,
        i: "d37f74a7a8",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 61,
        i: "930e9f345b",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 61,
        i: "c82867b745",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 64,
        i: "c8e550da12",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 61,
        i: "5dbba0fe80",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 64,
        i: "9186471baf",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 64,
        i: "f5bd10ee42",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 67,
        i: "19b3593ed5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 67,
        i: "dde0e8be14",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 67,
        i: "0269c95f63",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 67,
        i: "9cb15f60ba",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 70,
        i: "f69729e7b5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 70,
        i: "e627c1c5f0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 70,
        i: "d15926c8cb",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 70,
        i: "5f6ef96fc6",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 36,
        i: "fb5a6f0897",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 36,
        i: "d0e7c007f5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 36,
        i: "8d965cdf52",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 36,
        i: "7fb52e9770",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 39,
        i: "90a35fa878",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 39,
        i: "155ff2d875",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 39,
        i: "30cf12a087",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 39,
        i: "78cf00e1f9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 42,
        i: "6cf314bd85",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 42,
        i: "52a2bf75e7",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 42,
        i: "8ab672283a",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 42,
        i: "48fdd96cbc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 45,
        i: "388abfc1f8",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 64,
        i: "618e78a7b1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 45,
        i: "e65b21c429",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 45,
        i: "bbaa6ce2af",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 48,
        i: "10332c9560",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 48,
        i: "f20c00f856",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 48,
        i: "cf024244d9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 48,
        i: "ccdd313fec",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 51,
        i: "b73f5aa23c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 51,
        i: "5f9ce675c7",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 51,
        i: "86c8343c25",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 51,
        i: "6b0676bddf",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 54,
        i: "58b6908f5f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 54,
        i: "09f620d63f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 54,
        i: "5225b618ab",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 54,
        i: "126f717291",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 57,
        i: "5e4170fd3c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 57,
        i: "a757a9025f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 57,
        i: "eee0ca9574",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 57,
        i: "5d36ee57df",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 73,
        i: "4051731221",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 73,
        i: "807285da36",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 73,
        i: "159b206a7e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 73,
        i: "6fdd5f43c7",
        moved: false,
        static: false,
      },
    ],
  },
  widgets: [
    {
      id: "d5ce6b5379",
      content: "## 🪓 Martial Weapons! 🪓",
    },
    {
      id: "0e3cf44a7f",
      content: "## Type",
    },
    {
      id: "18f3580c70",
      content: "## **🪙**",
    },
    {
      id: "76c1b00605",
      content: "## 🩸",
    },
    {
      id: "b4d859a59c",
      content: "## 🔍",
    },
    {
      id: "bf018c61bd",
      content: "*🪓MARTIAL MELEE WEAPONS🪓*",
    },
    {
      id: "7103c78fba",
      content: "Battleaxe",
    },
    {
      id: "f7147315fc",
      content: "10gp",
    },
    {
      id: "f30c37510c",
      content: "1d8\n\nSlash",
    },
    {
      id: "4a71d65708",
      content: "Versatile (1d10)",
    },
    {
      id: "78926fb23f",
      content: "Flail",
    },
    {
      id: "93523da019",
      content: "10gp",
    },
    {
      id: "21ca77f398",
      content: "1d8\n\nBludge",
    },
    {
      id: "1ce4feba35",
      content: "NA",
    },
    {
      id: "4fcc0269d1",
      content: "Glaive",
    },
    {
      id: "bb1a28c7e9",
      content: "20gp",
    },
    {
      id: "e1a31dab10",
      content: "1d10\n\nSlash",
    },
    {
      id: "5817103e3f",
      content: "Heavy, reach, two-handed",
    },
    {
      id: "8c1b21c63e",
      content: "Greataxe",
    },
    {
      id: "5c69376534",
      content: "30gp",
    },
    {
      id: "91c319b58f",
      content: "1d12\n\nSlash",
    },
    {
      id: "b5332f99e0",
      content: "Heavy, two-handed",
    },
    {
      id: "d34083fadd",
      content: "Greatsword",
    },
    {
      id: "aba7240085",
      content: "50gp",
    },
    {
      id: "47344bb0ee",
      content: "2d6\n\nSlash",
    },
    {
      id: "b4e234f3c8",
      content: "Heavy, two-handed",
    },
    {
      id: "83fdd103b9",
      content: "Halberd",
    },
    {
      id: "2c70a86fcc",
      content: "20gp",
    },
    {
      id: "3a7bec4596",
      content: "1d10\n\nSlash",
    },
    {
      id: "4988fe75c6",
      content: "Heavy, reach, two-handed",
    },
    {
      id: "6c8a727f66",
      content: "Lance",
    },
    {
      id: "cb4dcf6889",
      content: "10gp",
    },
    {
      id: "026c9b7fb9",
      content: "1d12\n\nPierce",
    },
    {
      id: "e879ba1772",
      content: "Reach, special",
    },
    {
      id: "dd0637baff",
      content: "Longsword",
    },
    {
      id: "7d92fed9ca",
      content: "15gp",
    },
    {
      id: "af3ae00f32",
      content: "1d8\n\nSlash",
    },
    {
      id: "f83adfa0a4",
      content: "Versatile (1d10)",
    },
    {
      id: "7095234177",
      content: "Maul",
    },
    {
      id: "e53eb4dc8d",
      content: "10gp",
    },
    {
      id: "5266c25067",
      content: "2d6\n\nBludge",
    },
    {
      id: "3a09c6b35f",
      content: "Heavy, two-handed",
    },
    {
      id: "6f01bf04ae",
      content: "Morningstar",
    },
    {
      id: "40880d2424",
      content: "15gp",
    },
    {
      id: "1451e7e6f4",
      content: "1d8\n\nPierce",
    },
    {
      id: "5a90e2d138",
      content: "NA",
    },
    {
      id: "c09b8d6017",
      content: "*🪓MARTIAL RANGED WEAPONS🪓*",
    },
    {
      id: "0992628893",
      content: "Blowgun",
    },
    {
      id: "d37f74a7a8",
      content: "10gp",
    },
    {
      id: "930e9f345b",
      content: "1\n\nPierce",
    },
    {
      id: "c82867b745",
      content: "Ammo (80/32), loading, two-handed",
    },
    {
      id: "c8e550da12",
      content: "Crossbow, hand",
    },
    {
      id: "5dbba0fe80",
      content: "75gp",
    },
    {
      id: "9186471baf",
      content: "1d6\n\nPierce",
    },
    {
      id: "f5bd10ee42",
      content: "Ammo (30/120), light, loading",
    },
    {
      id: "19b3593ed5",
      content: "Crossbow, heavy",
    },
    {
      id: "dde0e8be14",
      content: "50gp",
    },
    {
      id: "0269c95f63",
      content: "1d10\n\nPierce",
    },
    {
      id: "9cb15f60ba",
      content: "Ammo (100/400), heavy, loading, two-handed",
    },
    {
      id: "f69729e7b5",
      content: "Longbow",
    },
    {
      id: "e627c1c5f0",
      content: "50gp",
    },
    {
      id: "d15926c8cb",
      content: "1d8\n\nPierce",
    },
    {
      id: "5f6ef96fc6",
      content: "Ammo (150/600), heavy, two-handed",
    },
    {
      id: "fb5a6f0897",
      content: "Pike",
    },
    {
      id: "d0e7c007f5",
      content: "5gp",
    },
    {
      id: "8d965cdf52",
      content: "1d10\n\nPierce",
    },
    {
      id: "7fb52e9770",
      content: "Heavy, reach, two-handed",
    },
    {
      id: "90a35fa878",
      content: "Rapier",
    },
    {
      id: "155ff2d875",
      content: "25gp",
    },
    {
      id: "30cf12a087",
      content: "1d8\n\nPierce",
    },
    {
      id: "78cf00e1f9",
      content: "Finesse",
    },
    {
      id: "6cf314bd85",
      content: "Scimitar",
    },
    {
      id: "52a2bf75e7",
      content: "25gp",
    },
    {
      id: "8ab672283a",
      content: "1d6\n\nSlash",
    },
    {
      id: "48fdd96cbc",
      content: "Finesse, light",
    },
    {
      id: "388abfc1f8",
      content: "Shortsword",
    },
    {
      id: "618e78a7b1",
      content: "10gp",
    },
    {
      id: "e65b21c429",
      content: "1d6\n\nPierce",
    },
    {
      id: "bbaa6ce2af",
      content: "Finesse, light",
    },
    {
      id: "10332c9560",
      content: "Trident",
    },
    {
      id: "f20c00f856",
      content: "5gp",
    },
    {
      id: "cf024244d9",
      content: "1d6\n\nPierce",
    },
    {
      id: "ccdd313fec",
      content: "Thrown (20/60), versatile (1d8)",
    },
    {
      id: "b73f5aa23c",
      content: "War pick",
    },
    {
      id: "5f9ce675c7",
      content: "5gp",
    },
    {
      id: "86c8343c25",
      content: "1d8\n\nPierce",
    },
    {
      id: "6b0676bddf",
      content: "NA",
    },
    {
      id: "58b6908f5f",
      content: "Warhammer",
    },
    {
      id: "09f620d63f",
      content: "15gp",
    },
    {
      id: "5225b618ab",
      content: "1d8\n\nBludge",
    },
    {
      id: "126f717291",
      content: "Versatile (1d10)",
    },
    {
      id: "5e4170fd3c",
      content: "Whip",
    },
    {
      id: "a757a9025f",
      content: "2gp",
    },
    {
      id: "eee0ca9574",
      content: "1d4\n\nSlash",
    },
    {
      id: "5d36ee57df",
      content: "Ammo (25/100), loading",
    },
    {
      id: "4051731221",
      content: "Net",
    },
    {
      id: "807285da36",
      content: "1gp",
    },
    {
      id: "159b206a7e",
      content: "NA",
    },
    {
      id: "6fdd5f43c7",
      content: "Special, thrown (5/15)",
    },
  ],
  isLocked: true,
};

export default martialWeaponsDashPremade;
