const simpleWeaponsDash = {
  layouts: {
    lg: [],
    md: [],
    sm: [],
    xs: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 8,
        h: 2,
        x: 0,
        y: 1,
        i: "d5ce6b5379",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 3,
        i: "0e3cf44a7f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 3,
        i: "18f3580c70",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 3,
        i: "76c1b00605",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 3,
        i: "b4d859a59c",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 5,
        i: "bf018c61bd",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 6,
        i: "7103c78fba",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 6,
        i: "f7147315fc",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 6,
        i: "f30c37510c",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 6,
        i: "4a71d65708",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 8,
        i: "78926fb23f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 8,
        i: "93523da019",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 8,
        i: "21ca77f398",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 8,
        i: "1ce4feba35",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 10,
        i: "4fcc0269d1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 10,
        i: "bb1a28c7e9",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 10,
        i: "e1a31dab10",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 10,
        i: "5817103e3f",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 12,
        i: "8c1b21c63e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 12,
        i: "5c69376534",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 12,
        i: "91c319b58f",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 12,
        i: "b5332f99e0",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 14,
        i: "d34083fadd",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 14,
        i: "aba7240085",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 14,
        i: "47344bb0ee",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 14,
        i: "b4e234f3c8",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 16,
        i: "83fdd103b9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 16,
        i: "2c70a86fcc",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 16,
        i: "3a7bec4596",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 16,
        i: "4988fe75c6",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 18,
        i: "6c8a727f66",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 18,
        i: "cb4dcf6889",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 18,
        i: "026c9b7fb9",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 18,
        i: "e879ba1772",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 20,
        i: "dd0637baff",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 20,
        i: "7d92fed9ca",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 20,
        i: "af3ae00f32",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 20,
        i: "f83adfa0a4",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 22,
        i: "7095234177",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 22,
        i: "e53eb4dc8d",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 22,
        i: "5266c25067",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 22,
        i: "3a09c6b35f",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 24,
        i: "6f01bf04ae",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 24,
        i: "40880d2424",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 24,
        i: "1451e7e6f4",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 24,
        i: "5a90e2d138",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 26,
        i: "c09b8d6017",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 27,
        i: "0992628893",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 27,
        i: "d37f74a7a8",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 27,
        i: "930e9f345b",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 27,
        i: "c82867b745",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 29,
        i: "c8e550da12",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 29,
        i: "5dbba0fe80",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 29,
        i: "9186471baf",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 29,
        i: "f5bd10ee42",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 31,
        i: "19b3593ed5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 31,
        i: "dde0e8be14",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 31,
        i: "0269c95f63",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 31,
        i: "9cb15f60ba",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 33,
        i: "f69729e7b5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 33,
        i: "e627c1c5f0",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 3,
        y: 33,
        i: "d15926c8cb",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 2,
        x: 5,
        y: 33,
        i: "5f6ef96fc6",
        moved: false,
        static: false,
      },
    ],
    xxs: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 1,
        i: "d5ce6b5379",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 0,
        y: 3,
        i: "0e3cf44a7f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 1,
        y: 3,
        i: "18f3580c70",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 2,
        y: 3,
        i: "76c1b00605",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 2,
        x: 3,
        y: 3,
        i: "b4d859a59c",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 5,
        i: "bf018c61bd",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 6,
        i: "7103c78fba",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 6,
        i: "f7147315fc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 6,
        i: "f30c37510c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 6,
        i: "4a71d65708",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 9,
        i: "78926fb23f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 9,
        i: "93523da019",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 9,
        i: "21ca77f398",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 9,
        i: "1ce4feba35",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 12,
        i: "4fcc0269d1",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 12,
        i: "bb1a28c7e9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 12,
        i: "e1a31dab10",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 12,
        i: "5817103e3f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 15,
        i: "8c1b21c63e",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 15,
        i: "5c69376534",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 15,
        i: "91c319b58f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 15,
        i: "b5332f99e0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 18,
        i: "d34083fadd",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 18,
        i: "aba7240085",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 18,
        i: "47344bb0ee",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 18,
        i: "b4e234f3c8",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 21,
        i: "83fdd103b9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 21,
        i: "2c70a86fcc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 21,
        i: "3a7bec4596",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 21,
        i: "4988fe75c6",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 24,
        i: "6c8a727f66",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 24,
        i: "cb4dcf6889",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 24,
        i: "026c9b7fb9",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 24,
        i: "e879ba1772",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 27,
        i: "dd0637baff",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 27,
        i: "7d92fed9ca",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 27,
        i: "af3ae00f32",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 27,
        i: "f83adfa0a4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 30,
        i: "7095234177",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 30,
        i: "e53eb4dc8d",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 30,
        i: "5266c25067",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 30,
        i: "3a09c6b35f",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 33,
        i: "6f01bf04ae",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 33,
        i: "40880d2424",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 33,
        i: "1451e7e6f4",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 33,
        i: "5a90e2d138",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 36,
        i: "c09b8d6017",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 37,
        i: "0992628893",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 37,
        i: "d37f74a7a8",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 37,
        i: "930e9f345b",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 37,
        i: "c82867b745",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 40,
        i: "c8e550da12",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 40,
        i: "5dbba0fe80",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 40,
        i: "9186471baf",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 40,
        i: "f5bd10ee42",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 43,
        i: "19b3593ed5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 43,
        i: "dde0e8be14",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 43,
        i: "0269c95f63",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 43,
        i: "9cb15f60ba",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 0,
        y: 46,
        i: "f69729e7b5",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 1,
        y: 46,
        i: "e627c1c5f0",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 2,
        y: 46,
        i: "d15926c8cb",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 3,
        x: 3,
        y: 46,
        i: "5f6ef96fc6",
        moved: false,
        static: false,
      },
    ],
  },
  widgets: [
    {
      id: "d5ce6b5379",
      content: "## 🗡️ Simple Weapons 🗡️",
    },
    {
      id: "0e3cf44a7f",
      content: "## Type",
    },
    {
      id: "18f3580c70",
      content: "## **🪙**",
    },
    {
      id: "76c1b00605",
      content: "## 🩸",
    },
    {
      id: "b4d859a59c",
      content: "## 🔍",
    },
    {
      id: "bf018c61bd",
      content: "*🗡️ SIMPLE MELEE WEAPONS 🗡️*",
    },
    {
      id: "7103c78fba",
      content: "Club",
    },
    {
      id: "f7147315fc",
      content: "1 sp",
    },
    {
      id: "f30c37510c",
      content: "1d4\n\nBludge",
    },
    {
      id: "4a71d65708",
      content: "Light",
    },
    {
      id: "78926fb23f",
      content: "Dagger",
    },
    {
      id: "93523da019",
      content: "2gp",
    },
    {
      id: "21ca77f398",
      content: "1d4\n\nPierce",
    },
    {
      id: "1ce4feba35",
      content: "Finesse, light, thrown (20/60)",
    },
    {
      id: "4fcc0269d1",
      content: "Greatclub",
    },
    {
      id: "bb1a28c7e9",
      content: "2sp",
    },
    {
      id: "e1a31dab10",
      content: "1d8\n\nBludge",
    },
    {
      id: "5817103e3f",
      content: "Two-Handed",
    },
    {
      id: "8c1b21c63e",
      content: "Handaxe",
    },
    {
      id: "5c69376534",
      content: "5gp",
    },
    {
      id: "91c319b58f",
      content: "1d6\n\nSlash",
    },
    {
      id: "b5332f99e0",
      content: "Light, thrown (20/60)",
    },
    {
      id: "d34083fadd",
      content: "Javelin",
    },
    {
      id: "aba7240085",
      content: "5sp",
    },
    {
      id: "47344bb0ee",
      content: "1d6\n\nPierce",
    },
    {
      id: "b4e234f3c8",
      content: "Thrown (30/120)",
    },
    {
      id: "83fdd103b9",
      content: "Light\n\nHammer",
    },
    {
      id: "2c70a86fcc",
      content: "2gp",
    },
    {
      id: "3a7bec4596",
      content: "1d4\n\nBludge",
    },
    {
      id: "4988fe75c6",
      content: "Light, thrown (20/60)",
    },
    {
      id: "6c8a727f66",
      content: "Mace",
    },
    {
      id: "cb4dcf6889",
      content: "5gp",
    },
    {
      id: "026c9b7fb9",
      content: "1d6\n\nBludge",
    },
    {
      id: "e879ba1772",
      content: "NA",
    },
    {
      id: "dd0637baff",
      content: "Quarterstaff",
    },
    {
      id: "7d92fed9ca",
      content: "2sp",
    },
    {
      id: "af3ae00f32",
      content: "1d6\n\nBludge",
    },
    {
      id: "f83adfa0a4",
      content: "Versatile (1d8)",
    },
    {
      id: "7095234177",
      content: "Sickle",
    },
    {
      id: "e53eb4dc8d",
      content: "1gp",
    },
    {
      id: "5266c25067",
      content: "1d4\n\nSlash",
    },
    {
      id: "3a09c6b35f",
      content: "Light",
    },
    {
      id: "6f01bf04ae",
      content: "Spear",
    },
    {
      id: "40880d2424",
      content: "1gp",
    },
    {
      id: "1451e7e6f4",
      content: "1d6\n\nPierce",
    },
    {
      id: "5a90e2d138",
      content: "Thrown (20/60), versatile (1d8)",
    },
    {
      id: "c09b8d6017",
      content: "*🗡️ SIMPLE RANGED WEAPONS 🗡️*",
    },
    {
      id: "0992628893",
      content: "Crossbow, light",
    },
    {
      id: "d37f74a7a8",
      content: "25gp",
    },
    {
      id: "930e9f345b",
      content: "1d8\n\nPierce",
    },
    {
      id: "c82867b745",
      content: "Ammo (80/32), loading, two-handed",
    },
    {
      id: "c8e550da12",
      content: "Dart",
    },
    {
      id: "5dbba0fe80",
      content: "5cp",
    },
    {
      id: "9186471baf",
      content: "1d4\n\nPierce",
    },
    {
      id: "f5bd10ee42",
      content: "Finesse, thrown (20/60)",
    },
    {
      id: "19b3593ed5",
      content: "Shortbow",
    },
    {
      id: "dde0e8be14",
      content: "25gp",
    },
    {
      id: "0269c95f63",
      content: "1d6\n\nPierce",
    },
    {
      id: "9cb15f60ba",
      content: "Ammo (80/320), two-handed",
    },
    {
      id: "f69729e7b5",
      content: "Sling",
    },
    {
      id: "e627c1c5f0",
      content: "1sp",
    },
    {
      id: "d15926c8cb",
      content: "1d4\n\nBludge",
    },
    {
      id: "5f6ef96fc6",
      content: "Ammo (30/120)",
    },
  ],
  isLocked: true,
};

export default simpleWeaponsDash;
