const skillsDashPremade = {
  layouts: {
    lg: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 1,
        i: "k8ImmbGkGl",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 2,
        i: "ZU2RckxmWK",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 3,
        i: "7xpuOI6sfc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 4,
        i: "wfrvF6BvCS",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 5,
        i: "9p8gIjJlEJ",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 6,
        i: "DHx3bkxmSN",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 7,
        i: "BByqLT9faI",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 8,
        i: "OZUNoz3uLc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 9,
        i: "4FSpl1gq2b",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 10,
        i: "hAPsu42bYn",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 11,
        i: "G4L5rtwq8c",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 12,
        i: "xx47RTdK8D",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 13,
        i: "AM0C70NsMf",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 14,
        i: "opfeJTjLDc",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 15,
        i: "X2UyC9y5jx",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 16,
        i: "1AAThpxnTW",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 17,
        i: "mLhA6aDirU",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 18,
        i: "HAybzKC3UV",
        moved: false,
        static: false,
      },
      {
        w: 1,
        h: 1,
        x: 0,
        y: 19,
        i: "YlDiVM4DMi",
        moved: false,
        static: false,
      },
    ],
    md: [],
    sm: [],
    xs: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 8,
        h: 2,
        x: 0,
        y: 1,
        i: "k8ImmbGkGl",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 3,
        x: 0,
        y: 3,
        i: "ZU2RckxmWK",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 3,
        x: 3,
        y: 3,
        i: "7xpuOI6sfc",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 3,
        x: 0,
        y: 7,
        i: "wfrvF6BvCS",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 7,
        i: "9p8gIjJlEJ",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 8,
        i: "DHx3bkxmSN",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 9,
        i: "BByqLT9faI",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 5,
        x: 0,
        y: 11,
        i: "OZUNoz3uLc",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 11,
        i: "4FSpl1gq2b",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 12,
        i: "hAPsu42bYn",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 13,
        i: "G4L5rtwq8c",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 14,
        i: "xx47RTdK8D",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 15,
        i: "AM0C70NsMf",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 5,
        x: 0,
        y: 17,
        i: "opfeJTjLDc",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 17,
        i: "X2UyC9y5jx",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 18,
        i: "1AAThpxnTW",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 19,
        i: "mLhA6aDirU",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 20,
        i: "HAybzKC3UV",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 21,
        i: "YlDiVM4DMi",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 4,
        x: 0,
        y: 23,
        i: "3rePmpT5aa",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 23,
        i: "3RuDu2MQe2",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 24,
        i: "ufZLd3m7h9",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 25,
        i: "TfIDMhKsBF",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 1,
        x: 3,
        y: 26,
        i: "ZfpXgSxS2X",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 6,
        i: "z7jQRVHbkw",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 10,
        i: "2DGYVpttJO",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 16,
        i: "TueJaDlYq1",
        moved: false,
        static: false,
      },
      {
        w: 8,
        h: 1,
        x: 0,
        y: 22,
        i: "jcomtgjfV1",
        moved: false,
        static: false,
      },
    ],
    xxs: [
      {
        w: 1,
        h: 1,
        x: 0,
        y: 0,
        i: "New Widget",
        moved: false,
        static: true,
        isDraggable: false,
        isResizable: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 1,
        i: "k8ImmbGkGl",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 4,
        x: 0,
        y: 3,
        i: "ZU2RckxmWK",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 7,
        i: "7xpuOI6sfc",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 4,
        x: 0,
        y: 10,
        i: "wfrvF6BvCS",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 14,
        i: "9p8gIjJlEJ",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 16,
        i: "DHx3bkxmSN",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 18,
        i: "BByqLT9faI",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 4,
        x: 0,
        y: 21,
        i: "OZUNoz3uLc",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 25,
        i: "4FSpl1gq2b",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 27,
        i: "hAPsu42bYn",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 29,
        i: "G4L5rtwq8c",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 31,
        i: "xx47RTdK8D",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 33,
        i: "AM0C70NsMf",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 4,
        x: 0,
        y: 36,
        i: "opfeJTjLDc",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 40,
        i: "X2UyC9y5jx",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 42,
        i: "1AAThpxnTW",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 44,
        i: "mLhA6aDirU",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 46,
        i: "HAybzKC3UV",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 48,
        i: "YlDiVM4DMi",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 4,
        x: 0,
        y: 51,
        i: "3rePmpT5aa",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 55,
        i: "3RuDu2MQe2",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 57,
        i: "ufZLd3m7h9",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 59,
        i: "TfIDMhKsBF",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 2,
        x: 0,
        y: 61,
        i: "ZfpXgSxS2X",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 9,
        i: "z7jQRVHbkw",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 20,
        i: "2DGYVpttJO",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 35,
        i: "TueJaDlYq1",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 1,
        x: 0,
        y: 50,
        i: "jcomtgjfV1",
        moved: false,
        static: false,
      },
    ],
  },
  widgets: [
    {
      id: "k8ImmbGkGl",
      content: "## &#x20;🧮 Skills 🧮",
    },
    {
      id: "ZU2RckxmWK",
      content: "## Strength 💪",
    },
    {
      id: "7xpuOI6sfc",
      content: "### Athletics 🏃",
    },
    {
      id: "wfrvF6BvCS",
      content: "## Dexterity 💨",
    },
    {
      id: "9p8gIjJlEJ",
      content: "### Acrobatics 🤸",
    },
    {
      id: "DHx3bkxmSN",
      content: "### Slight of Hand 🤏",
    },
    {
      id: "BByqLT9faI",
      content: "### Stealth 🥷",
    },
    {
      id: "OZUNoz3uLc",
      content: "## Intelligence 🧠",
    },
    {
      id: "4FSpl1gq2b",
      content: "### Arcana 📜",
    },
    {
      id: "hAPsu42bYn",
      content: "### History 🏺",
    },
    {
      id: "G4L5rtwq8c",
      content: "### Investigation 🔍",
    },
    {
      id: "xx47RTdK8D",
      content: "### Nature 🌱",
    },
    {
      id: "AM0C70NsMf",
      content: "### Religion 🛐",
    },
    {
      id: "opfeJTjLDc",
      content: "## Wisdom 🦉",
    },
    {
      id: "X2UyC9y5jx",
      content: "### Animal Handling 🏇",
    },
    {
      id: "1AAThpxnTW",
      content: "### Insight 🤔",
    },
    {
      id: "mLhA6aDirU",
      content: "### Medicine ⚕️",
    },
    {
      id: "HAybzKC3UV",
      content: "### Perception 👁️",
    },
    {
      id: "YlDiVM4DMi",
      content: "### Survival 🏕️",
    },
    {
      id: "3rePmpT5aa",
      content: "## Charisma 😎",
    },
    {
      id: "3RuDu2MQe2",
      content: "### Deception 😉",
    },
    {
      id: "ufZLd3m7h9",
      content: "### Intimidation 👺",
    },
    {
      id: "TfIDMhKsBF",
      content: "### Performance 🎭",
    },
    {
      id: "ZfpXgSxS2X",
      content: "### Persuasion 😏",
    },
    {
      id: "z7jQRVHbkw",
      content: "",
    },
    {
      id: "2DGYVpttJO",
      content: "",
    },
    {
      id: "TueJaDlYq1",
      content: "",
    },
    {
      id: "jcomtgjfV1",
      content: "",
    },
  ],
  isLocked: true,
};

export default skillsDashPremade;
